hello

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -19,6 +19,8 @@ jobs:
           override: true
     - name: build Rust
       run: make build
+    - name : Copy
+      run : make copy
     - name: Format
       run: make format
     - name: Lint
@@ -26,14 +28,28 @@ jobs:
     - name: Test
       run: make test   
     - name: Build
-      run: | 
-        echo "RUST CRUD OPERATIONS" > output.txt
-
-    - name: Publish Artifact
-      uses: actions/upload-artifact@v2
-      with:
-        name: my-artifact
-        path: output.txt
+      run: make build
+    - name: Archive and Upload Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: ml_pipeline-artifacts
+          path: ${{ github.workspace }}
+        
+      - name: Save to repository
+        env:
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+        run: |
+          echo GH_TOKEN: "${GH_TOKEN}"
+          git config --global user.name 'github-actions'
+          git config --local user.email "action@github.com"
+          git add Rust_Binary
+          git commit -m "Added Results" || echo "ignore commit failure, proceed"
+          git push
+      - name: Publish Artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: my-artifact
+          path: Binary_Executable
 
   deploy:
     needs: build
@@ -45,6 +61,4 @@ jobs:
       with:
         name: my-artifact
         path: downloaded-artifact
-
-    - name: Display Artifact
-      run: cat downloaded-artifact/output.txt
+    
